
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXlPVEF5TVRNd00xb1hEVE16TURZeU5qQXlNVE13TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjhtCnl1aW9lUmlYMU01akxub3gza3hBcWhRMjM2R2VPcnh2enQ2UTdZTEZTZ2QwVFFQUnV1dGhrUDRPNWtLMFkyTUIKeGUyaDdicnJ2QW43UjVqakZ5VitrQWxzVE5pdlF3TUpoa0lCL2pSZWl6YVdmckE5OVAwRTNib3F3cGpkNm90SQpJRkh6K2hQekNOelpoV041dzZtSU55YmZ6Mk1Pd011d3NqQVVjVmFmM0JZSzlackZxRlMrcFRtMU5KTU1rUnBCCk9YMmlDYXBQSmwxQ0FEeGIvdDdTZHFnc09iSEQ2TFl3aExXZ2JjOGUwa01oRFdpczRBWHB4YkUyMkY2ZmVVbXgKWWFJcnJOUkN6bVllbFZEa2VoN2duM2F4cUJzYjdKVTRDb1Jaa25mTTIrb0UrQTlzekJvTHN5TFQ1VmpGWTEwQwpVaW5IRHpIcGlYaWI3QXhBRHFjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZENmM4WnpsSnRVaWEzb3NwR0ZHaFJROFdSWUlNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRm9UWXpVZ2s2MkV5cWtIU28wVApSSGxKVGhhUlFleEtXNEFsRDhOOStDeEtyUmRaN1c4WFpVeldyMEZrTWsrKzZZWjJ2S24rMVo1S0NCSDNLV3ZHCi8yZzhMRzF3T0E4bndDTGJ6N29kTTFyaGxuS0dXSCs0UEE4YkZOVHRBWXJjdDVJN2Y3OWxybGZHcjV1eHRiaEQKTFBwY0RTWkx0M2NTTitIVmx3dkVTTW45eVhJeGltdzZjWFJPUmFCUE1keDBXUnArVEU1b1ZmcmgrcjBSSHdTWgpnekF0VTg0V3E5T0RwSW9OWFlKVGlNak45UHdGVnBidFczTGJDaEErYm9EOFFyYlp3UktKWFR6L3ZtVG9KMFpjClZaL2tsYlNXMlhMakIvOERTZER3emg4aytHZDNBeWlqME5aTlVUYWFjY3R1NXRibThLYlZadERBOS8wcCtOK1MKQmRZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://e2a77495-774c-487c-841e-e3f07a2441d7.cpc1-us-central.linodelke.net:443
  name: lke116717

users:
- name: lke116717-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlhQam5NNllpUXFXODJsSXM0dF9hd290RGxnRWsyR2twbGFCRmNMUFRlZzgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZ3hqNHEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiM2NkYWE5NDAtYTQ0NS00YmRkLWIwN2EtOGE2NjRmNjA5NTQ3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.e_ZgVSUDxRZQJSfJMrvNLzWKWplgisReJzBJxkssTy_8De68z4yq6IJUlso4IWmienU2YjBlFgmP9hSkQ0xfV4rzvw1gEEoq62OiHj51dHukImD05KVt7PgxspaUJcuLMJWrUOxLDJMuUQQ2VQMYQ3FAIqYCQiF8UwQac9mEqsSX4G2Q6d5RMeb96bv8bhlHoKwegC0QeEiw35zEfy4mzx2lBs8f7tNn3mejzfLg_9XrKyfM210dY7fM4A0I-FpgtLBkHgIPnD8YM9twZ0G6tANmRkXWn6uuIxqhGY2Mlg3WfXZvOdZVwEJ3NLQOJ3zTnFeqAnKQRdLZCMZMNBQdJQ

contexts:
- context:
    cluster: lke116717
    namespace: default
    user: lke116717-admin
  name: lke116717-ctx

current-context: lke116717-ctx
