name: CI with maven 

on:
  push:
    branches: [ yannick ]
  pull_request:
    branches: [ yannick ]

env:
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # - name: clean the application 
    #   run: mvn -s settings.xml -DskipTests install

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run SonnarQube analysis
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=MyProject -Dsonar.host.url=http://54.176.196.57 -Dsonar.login=$SONAR_TOKEN

    

